# 確定版マッピング: (現ファイル名, 撮影地, 新ファイル名 or None=退避)
FINAL = [
("couple-01.jpg","神社","prewedding-kimono-wagasa-shrine.jpg"),
("couple-02.jpg","和室","prewedding-kimono-engawa.jpg"),
("couple-03.jpg","和室","prewedding-kimono-tatami-room.jpg"),
("couple-04.jpg","和室","prewedding-kimono-couple-closeup.jpg"),
("landscape-01.jpg","代々木公園駅裏","yoyogi-koen-backstreet-night.jpg"),
("landscape-02.jpg","江ノ島","enoshima-island-dusk.jpg"),
("landscape-03.jpg","羽田空港","haneda-mount-fuji-aircraft-sunset.jpg"),
("landscape-04.jpg","羽田空港","haneda-sunset-through-glass.jpg"),
("landscape-05.jpg","AKAO Forest (熱海)","atami-akao-forest-hibiscus.jpg"),
("landscape-06.jpg","江ノ島","enoshima-rough-waves-dusk.jpg"),
("landscape-07.jpg","羽田空港","haneda-control-tower-silhouette.jpg"),
("landscape-08.jpg","AKAO Forest (熱海)","atami-akao-forest-pine-white-sand.jpg"),
("landscape-09.jpg","AKAO Forest (熱海)","atami-akao-forest-garden-vista.jpg"),
("landscape-10.jpg","片瀬海岸","katase-beach-summer-end.jpg"),
("landscape-11.jpg","片瀬海岸","katase-beach-palm-street-twilight.jpg"),
("landscape-12.jpg","江ノ島","enoshima-night-gate.jpg"),
("landscape-13.jpg","江ノ島","enoshima-path-to-the-sea.jpg"),
("landscape-14.jpg","江ノ電沿線","enoden-night-crossing.jpg"),
("landscape-15.jpg","羽田空港 第2ターミナル","haneda-t2-runway-lights-night.jpg"),
("landscape-16.jpg","東京駅","tokyo-station-red-brick.jpg"),
("landscape-17.jpg","横浜みなとみらい","yokohama-minatomirai-dusk.jpg"),
("landscape-18.jpg","横浜みなとみらい","yokohama-cosmo-clock-night.jpg"),
("landscape-19.jpg","札幌 大通公園","sapporo-tv-tower-lilac.jpg"),
("landscape-20.jpg","札幌 大通公園","sapporo-tv-tower-through-lilac.jpg"),
("landscape-21.jpg","札幌 大通公園","sapporo-odori-tulips.jpg"),
("landscape-22.jpg","札幌 大通公園","sapporo-odori-spring-flowerbed.jpg"),
("landscape-23.jpg","平岡公園 (北海道)","sapporo-hiraoka-park-azalea-hill.jpg"),
("landscape-24.jpg","平岡公園 (北海道)","sapporo-hiraoka-park-azalea-closeup.jpg"),
("landscape-25.jpg","平岡公園 (北海道)","sapporo-hiraoka-park-plum-blossoms.jpg"),
("landscape-26.jpg","平岡公園 (北海道)","sapporo-hiraoka-park-fresh-green-maple.jpg"),
("landscape-27.jpg","札幌","sapporo-koinobori.jpg"),
("landscape-28.jpg","札幌","sapporo-koinobori-may-sky.jpg"),
("landscape-29.jpg","札幌","sapporo-koinobori-wind.jpg"),
("landscape-30.jpg","札幌","sapporo-spring-red-leaves.jpg"),
("landscape-31.jpg","札幌 大通公園","sapporo-odori-fountain.jpg"),
("landscape-32.jpg","札幌 大通公園","sapporo-odori-fountain-afternoon.jpg"),
("landscape-33.jpg","平岡公園 (北海道)","sapporo-hiraoka-park-white-blossom-tree.jpg"),
("city-01.jpg","札幌 北海道庁旧本庁舎","sapporo-akarenga-government-office.jpg"),
("city-02.jpg","札幌 北海道庁旧本庁舎","sapporo-akarenga-spring.jpg"),
("city-03.jpg","札幌 北海道庁旧本庁舎","sapporo-akarenga-facade.jpg"),
("city-04.jpg","札幌 北海道庁旧本庁舎","sapporo-akarenga-ceiling.jpg"),
("city-05.jpg","札幌 北海道庁旧本庁舎","sapporo-akarenga-arch.jpg"),
("city-06.jpg","札幌 大通","sapporo-odori-afternoon.jpg"),
("city-07.jpg","札幌 駅前通","sapporo-ekimae-street.jpg"),
("city-08.jpg","札幌 すすきの","sapporo-susukino-evening.jpg"),
("city-09.jpg","平岡公園 (北海道)","sapporo-hiraoka-park-tree-lined-path.jpg"),
("city-10.jpg","札幌 JRタワー","sapporo-jr-tower-night-dusk.jpg"),
("city-11.jpg","札幌 JRタワー","sapporo-jr-tower-night-blue-hour.jpg"),
("city-12.jpg","札幌 JRタワー","sapporo-jr-tower-night-ultramarine.jpg"),
("city-13.jpg","札幌 JRタワー","sapporo-jr-tower-night-sea-of-lights.jpg"),
("city-14.jpg","札幌 JRタワー","sapporo-jr-tower-night-distant-lights.jpg"),
("portrait-01.jpg","江ノ島シーキャンドル","enoshima-sea-candle-dog.jpg"),
("portrait-02.jpg","裏渋谷","shibuya-backstreet-night.jpg"),
("portrait-03.jpg","羽田空港 第3ターミナル","haneda-t3-departure-hall.jpg"),
("portrait-04.jpg","AKAO Forest (熱海)","atami-akao-forest-gazing-at-sea.jpg"),
("portrait-05.jpg","横浜 大さん橋","yokohama-osanbashi-night.jpg"),
("portrait-06.jpg","高輪ゲートウェイ","takanawa-gateway-cafe-coffee.jpg"),
("portrait-07.jpg","高輪ゲートウェイ","takanawa-gateway-smart-lounge.jpg"),
("portrait-08.jpg","AKAO Forest (熱海)","atami-akao-forest-entrance-sign.jpg"),
("portrait-09.jpg","熱海","atami-japanese-gate.jpg"),
("portrait-10.jpg","羽田空港 第3ターミナル","haneda-t3-terminal-interior.jpg"),
("portrait-11.jpg","羽田空港 第3ターミナル","haneda-t3-nice-day-sign.jpg"),
("snap-01.jpg","平岡公園 (北海道)","sapporo-hiraoka-park-dog-walk.jpg"),
("snap-02.jpg","平岡公園 (北海道)","sapporo-hiraoka-park-walk.jpg"),
("aviation-01.jpg","羽田空港","haneda-jal-a350-night-pushback.jpg"),
("aviation-02.jpg","羽田空港","haneda-jal-767-dawn.jpg"),
("aviation-03.jpg","羽田空港","haneda-pokemon-jet-sea.jpg"),
("aviation-04.jpg","羽田空港","haneda-oneworld-787-golden-hour.jpg"),
("aviation-05.jpg","羽田空港","haneda-oneworld-jal-sea.jpg"),
("aviation-06.jpg","羽田空港","haneda-ana-787-departure.jpg"),
("aviation-07.jpg","羽田空港","haneda-jal-shohei-jet.jpg"),
("aviation-08.jpg","羽田空港","haneda-ana-767-panning.jpg"),
("aviation-09.jpg","羽田空港","haneda-jal-767-dusk-panning.jpg"),
("aviation-10.jpg","羽田空港","haneda-ana-morning-mist.jpg"),
("aviation-11.jpg","羽田空港","haneda-ana-787-nose-night.jpg"),
("aviation-12.jpg","羽田空港","haneda-jal-a350-lineup.jpg"),
("aviation-13.jpg","羽田空港","haneda-oneworld-a350-apron.jpg"),
("aviation-14.jpg","羽田空港","haneda-jal-a350-runway.jpg"),
("aviation-15.jpg","羽田 JAL格納庫",None),
("aviation-16.jpg","羽田 JAL格納庫",None),
("aviation-17.jpg","羽田 JAL格納庫",None),
("aviation-18.jpg","羽田 JAL格納庫",None),
("aviation-19.jpg","羽田 JAL格納庫",None),
("aviation-20.jpg","羽田 JAL格納庫",None),
("aviation-21.jpg","羽田 JAL格納庫",None),
("aviation-22.jpg","羽田 JAL格納庫",None),
("aviation-23.jpg","羽田 JAL格納庫",None),
("aviation-24.jpg","羽田 JAL格納庫",None),
("aviation-25.jpg","羽田 JAL格納庫",None),
("aviation-26.jpg","伊丹スカイパーク","itami-ana-787-head-on-dusk.jpg"),
("aviation-27.jpg","伊丹スカイパーク","itami-runway-lights-dusk.jpg"),
("aviation-28.jpg","伊丹スカイパーク","itami-ana-737-against-the-ridge.jpg"),
("aviation-29.jpg","伊丹スカイパーク","itami-ana-787-nose-close-up.jpg"),
("aviation-30.jpg","伊丹スカイパーク","itami-ana-787-panning.jpg"),
("aviation-31.jpg","伊丹スカイパーク","itami-ana-panning-dusk.jpg"),
("aviation-32.jpg","伊丹スカイパーク","itami-skypark-photographer.jpg"),
("aviation-33.jpg","伊丹スカイパーク","itami-jac-turboprop-orange.jpg"),
("aviation-34.jpg","伊丹スカイパーク","itami-ana-nose-blue.jpg"),
("aviation-35.jpg","伊丹スカイパーク","itami-climb-over-the-hills.jpg"),
("aviation-36.jpg","伊丹スカイパーク","itami-ana-over-the-city.jpg"),
("aviation-37.jpg","伊丹スカイパーク","itami-ana-737-rotation.jpg"),
("aviation-38.jpg","伊丹スカイパーク","itami-landing-lights-head-on.jpg"),
("aviation-39.jpg","伊丹スカイパーク","itami-jal-787-into-the-blue.jpg"),
("aviation-40.jpg","伊丹スカイパーク","itami-down-the-runway.jpg"),
("aviation-41.jpg","伊丹スカイパーク","itami-jal-787-at-dusk.jpg"),
("aviation-42.jpg","伊丹スカイパーク","itami-ana-at-dusk.jpg"),
("aviation-43.jpg","伊丹スカイパーク","itami-terminal-at-night.jpg"),
("aviation-44.jpg","伊丹スカイパーク","itami-terminal-lights.jpg"),
("aviation-45.jpg","伊丹スカイパーク","itami-sunflowers-by-the-runway.jpg"),
]
NEW13 = [
("itami-jal-787-departure-sky.jpg","伊丹スカイパーク"),
("itami-jal-737-runway-flowers.jpg","伊丹スカイパーク"),
("itami-ana-737-taxiing-flowers.jpg","伊丹スカイパーク"),
("itami-ana-737-landing-through-trees.jpg","伊丹スカイパーク"),
("itami-ana-737-takeoff-mountains.jpg","伊丹スカイパーク"),
("itami-sunflowers-summer-sky.jpg","伊丹スカイパーク"),
("itami-sunflowers-vertical.jpg","伊丹スカイパーク"),
("itami-sunflowers-blue-hour.jpg","伊丹スカイパーク"),
("itami-ana-a320-panning-dusk.jpg","伊丹スカイパーク"),
("itami-jal-767-sunset-mountains.jpg","伊丹スカイパーク"),
("itami-jac-turboprop-evening.jpg","伊丹スカイパーク"),
("itami-terminal-night-view.jpg","伊丹スカイパーク"),
("itami-airport-sign-night.jpg","伊丹スカイパーク"),
]
